name: Pull request workflow

on:
  pull_request:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:  
  build-image:
    needs: artifact-tag
    uses: ./.github/workflows/workflow-build-image.yaml
    secrets: inherit
    with:
      aws-role-arn: "arn:aws:iam::102867326982:role/GithubDevCDRole"
      registry: "102867326982.dkr.ecr.us-east-1.amazonaws.com"
      image-uri: "102867326982.dkr.ecr.us-east-1.amazonaws.com/rights-manager/application:${{ needs.artifact-tag.outputs.artifact-tag }}"
      image-version: "${{ needs.artifact-tag.outputs.image-version }}"
  pull-request-output:
    runs-on: ubuntu-latest
    needs: [build-image, artifact-tag]
    steps:
      - name: Comment artifact to PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "📦 Artifacts Tag: `${{ needs.artifact-tag.outputs.artifact-tag }}`"
          delete_prev_regex_msg: "📦 Artifacts Tag:"