name: Build image

on:
  workflow_call:
    inputs:
      aws-role-arn:
        required: true
        type: string
      registry:
        required: true
        type: string
      image-uri:
        required: true
        type: string
      image-version:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "${{ inputs.aws-role-arn }}"
          aws-region: "us-east-1"

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: "${{ inputs.registry }}"

      - name: Build And Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "${{ inputs.image-uri }}"
          cache-to: "type=inline"
          build-args: |
            "APPLICATION_VERSION=${{ inputs.image-version }}"